version: '3.8'

services:

  projects:
    build:  ./
    command: ./projects
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    image: postgres:latest
    env_file:
      - ./.env
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
